[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["ryuseikakujo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.25.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
